name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: install pip and python dependency
        run: |
           sudo apt update
           sudo apt install python3.8

      - name: install pip and python dependency
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install --upgrade acryl-datahub

      - name: Deploy datahub
        run: datahub docker quickstart

