name: Deploy DataHub on EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: actions/setup-ssh@v3
        with:
          github-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to EC2 instance
        uses: easingthemes/ssh-deploy@main
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          user: ${{ secrets.EC2_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create a file
        run: mkdir mahesh

      - name: Upgrade PIP
        run: python3 -m pip install --upgrade pip wheel setuptools

      - name: Install Acryl DataHub
        run: python3 -m pip install --upgrade acryl-datahub

      - name: Check DataHub version
        run: datahub version

      - name: Start DataHub container
        run: datahub docker quickstart

